# Generated by Django 4.2.1 on 2023-07-17 19:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='product',
        #     old_name='product_image',
        #     new_name='product_image',
        # ),
        migrations.AddField(
            model_name='product',
            name='org_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sel_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
